apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-wiki-data-volume-claim
  namespace: dev-wiki
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi
---
# db volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-wiki-db-volume
  namespace: dev-wiki
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi